export const themeColors = {
  animals: "green",
  children: "blue",
  climate: "teal",
  democ: "yellow",
  disaster: "red",
  ecdev: "indigo",
  edu: "purple",
  env: "green",
  gender: "pink",
  health: "red",
  human: "yellow",
  rights: "blue",
  sport: "indigo",
  tech: "purple",
  hunger: "yellow",
  art: "orange",
  lgbtq: "rainbow", // Custom color, not a default Tailwind color
  "covid-19": "blue",
  water: "teal",
  disability: "gray",
  endabuse: "pink",
  mentalhealth: "indigo",
  justice: "gray",
  refugee: "gray",
  reproductive: "pink",
  housing: "orange",
  agriculture: "green",
  wildlife: "green",
};
